/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: '实现 OpenSDD 变更中的任务。当用户想要开始实现、继续实现或处理任务时使用。',
    instructions: ``,
    license: 'MIT',
    compatibility: '需要 opensdd CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Apply',
    description: '实现变更中的任务',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `# 实现变更中的任务。

**输入**：可选择指定变更名称（例如，\`/opsx:apply add-auth\`）。如果省略，检查是否可以从对话上下文中推断出来。如果模糊或不明确，你必须提示可用的变更。

## 流程详述
### 实施修改前

**选择变更**

   如果提供了名称，使用它。否则：
   - 如果用户提到了某个变更，从对话上下文中推断
   - 如果只存在一个活动变更，自动选择
   - 如果不明确，运行 \`opensdd list --json\` 获取可用变更，并使用 **AskUserQuestion tool** 让用户选择

   始终宣布："正在使用变更：<name>"以及如何覆盖（例如，\`/opsx:apply <other>\`）。

**检查状态以了解 Schema**
   \`\`\`bash
   opensdd status --change "<name>" --json
   \`\`\`
   解析 JSON 以了解：
   - \`schemaName\`：正在使用的工作流 Schema（例如："spec-driven"）
   - 哪个产出物包含任务（对于 spec-driven 是 "plan"，检查其他产出物的状态）

**阅读上下文文件**

   阅读 apply instructions 输出中 \`contextFiles\` 列出的每个文件路径。
   文件取决于正在使用的 Schema：
   - **spec-driven**: specs, design, plan
   - 其他模式：遵循 CLI 输出中的 contextFiles

**显示当前进度**

   显示：
   - 正在使用的 Schema
   - 进度："N/M 任务已完成"

### 任务实施（调用子智能体驱动开发技能）

   **无人值守原则：** 一旦进入实现阶段，自主推进所有任务直到全部完成。遇到问题时自行解决，不暂停等待用户介入。

   **加载 \`subagent-driven-development\` 技能，严格按照该技能的流程执行所有任务。**

   该技能会自动执行：为每个任务分派隔离的实现子智能体 → 规格合规审查 → 代码质量审查 → 标记完成 → 继续下一个任务。你只需确保传递正确的上下文（完整任务文本 + 场景铺设 + 工作目录），其余流程由技能驱动。

### 任务完成（带变更级验证）

   **获取应用指令**

   \`\`\`bash
   opensdd instructions apply --change "<name>" --json
   \`\`\`

   这返回：
   - \`contextFiles\`：产出物 ID -> 具体文件路径数组（因 Schema 而异）
   - 进度（总计、完成、剩余）
   - 带有状态的任务列表
   - 基于当前状态的动态指令

   **处理状态：**
   - 如果 \`state: "blocked"\`（缺少产出物）：显示消息
   - 如果 \`state: "all_done"\`：祝贺，建议归档
   - 否则：继续实现

   **门控执行**
   所有任务完成后，执行验证门控。铁律：**没有新鲜的验证证据，不许宣称完成。**

   如果你在验证时没有运行命令，就不能声称所有任务已完成。跳过任何一步 = 说谎，不是验证。

   验证门控：
   1. **确定：** 什么命令能证明所有变更已正确完成？
   2. **运行：** 执行项目的完整构建命令和完整测试套件（重新运行，完整执行）
   3. **阅读：** 完整输出，检查退出码，统计失败数
   4. **验证：** 输出是否支持"变更已完成"这个结论？
      - 如果否：用证据说明实际状态，自行修复问题，重新验证
      - 如果是：带证据陈述结论
   5. **只有这时：** 才能宣称完成

   常见失败模式——以下证据**不够格**：
   - "之前的运行结果"、"应该会通过" → 不够格，需要新鲜的测试命令输出
   - 部分检查、推断 → 不够格，需要完整输出
   - 代理报告"成功" → 不够格，需要 VCS diff 或构建输出
   - "测试通过了" → 不够格，需要逐项核对清单

   红线——停下来重新验证：
   - 使用"应该"、"大概"、"似乎"
   - 验证前就表达满意（"太好了！"、"完美！"、"搞定！"等）
   - **任何暗示成功但实际未运行验证的措辞**

   防止合理化：
   - "应该能行了" → 运行验证命令
   - "我有信心" → 信心 ≠ 证据
   - "代理说成功了" → 独立验证
   - "部分检查就够了" → 部分检查什么也证明不了

   **验证没有捷径。运行命令。阅读输出。然后才能宣称结果。这没有商量余地。**

   验证通过后显示：
   - 本次会话完成的任务（附审查结果）
   - 总体进度："N/M 任务已完成"
   - 变更级验证结果：构建 ✅/❌（附命令和 exit code），测试 ✅/❌（附通过数）
   - 建议归档

   **验证失败时：**
   - 自行修复问题，不暂停等待用户
   - 修复后重新执行验证门控
   - 只有在反复修复仍无法通过时才暂停报告

**完成时的输出**

\`\`\`
## 实现完成

**变更：** <change-name>
**Schema：** <schema-name>
**进度：** 7/7 任务已完成 ✓

### 变更级验证
- **构建：** \`npm run build\` → exit 0 ✅
- **测试：** \`npm test\` → 34/34 pass ✅

### 本次会话已完成
- [x] 任务 3：<description>
- [x] 任务 4：<description>
...

所有任务已完成并通过验证！可以使用 \`/opsx:archive\` 归档此变更。
\`\`\`

**暂停时的输出（仅在反复自主修复仍无法通过时）**

\`\`\`
## 实现暂停——需要人工介入

**变更：** <change-name>
**Schema：** <schema-name>
**进度：** 4/7 任务已完成

### 已自主尝试的解决措施
1. <尝试 1：例如，换更强模型重新分派>
2. <尝试 2：例如，拆分任务后重新分派>

### 仍无法解决的问题
任务 5：<具体阻塞原因>

**已完成任务：**
- [x] 任务 1-4
\`\`\`

**护栏**

- 开始前始终阅读上下文文件（来自 apply instructions 输出）
- 使用 CLI 输出中的 contextFiles，不要假设特定的文件名
- 保持代码更改最小化并限定在每个任务范围内
- 实施阶段的子智能体纪律、审查流程、验证纪律全部由 \`subagent-driven-development\` 技能定义，严格遵循该技能的红线和要求

**流畅的工作流集成**

此技能支持"变更上的操作"模型：

- **可以随时调用**：在所有产出物完成之前（如果存在任务），部分实现之后，与其他操作交错
- **允许产出物更新**：如果实现揭示了设计问题，建议更新产出物 - 不是阶段锁定的，流畅地工作`
  };
}
